// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvbeqmtafjmebiqtkhtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2YmVxbXRhZmptZWJpcXRraHRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTQzMzcsImV4cCI6MjA2NTE3MDMzN30.zZfjb4IO4MEE72x1hn-PtMo7g2aMLg0Q6fv_nYo_mWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);